package com.sparrowwallet.sparrow.io;

import com.sparrowwallet.drongo.Network;
import com.sparrowwallet.drongo.policy.PolicyType;
import com.sparrowwallet.drongo.protocol.ScriptType;
import com.sparrowwallet.drongo.wallet.Keystore;
import com.sparrowwallet.drongo.wallet.MnemonicException;
import com.sparrowwallet.drongo.wallet.Wallet;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

/**
 * LOCAL-ONLY parity test (not for commit): verifies that a wallet file exported by
 * Sparrow-LTC Mobile (mobile/vectors/mobile-export-vector-wallet, regenerated by the
 * mobile repo's SparrowExportTest with password "pass" and Argon2 TEST_PARAMETERS)
 * loads and decrypts correctly under the desktop persistence stack. Mirrors
 * StorageTest.loadSeedWallet: after DB migration a seed wallet re-derives its
 * fingerprint/xpub from the decrypted seed.
 */
public class MobileExportTest {
    private static final String MNEMONIC =
            "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";

    @Test
    public void loadsMobileExportedWallet() throws IOException, MnemonicException, StorageException {
        File vector = new File("../mobile/vectors/mobile-export-vector-wallet");
        Assertions.assertTrue(vector.exists(), "run mobile SparrowExportTest first to regenerate the vector");

        // work on a temp copy: loadEncryptedWallet migrates JSON wallets to DB in place,
        // consuming the original file
        File tempDir = Files.createTempDirectory("mobile-export-test").toFile();
        File file = new File(tempDir, "mobile-export-vector-wallet");
        Files.copy(vector.toPath(), file.toPath());

        // what mobile wrote into the JSON (pre-migration), for cross-checking below
        Wallet jsonWallet = new JsonPersistence().loadWallet(new Storage(file), "pass").getWallet();
        String mobileXpub = jsonWallet.getKeystores().get(0).getExtendedPublicKey().toString();
        Assertions.assertEquals("73c5da0a", jsonWallet.getKeystores().get(0).getKeyDerivation().getMasterFingerprint());

        Storage storage = new Storage(file);
        WalletAndKey walletAndKey = storage.loadEncryptedWallet("pass");
        Wallet wallet = walletAndKey.getWallet();

        Assertions.assertEquals("Mobile Export", wallet.getName());
        Assertions.assertEquals(Network.MAINNET, wallet.getNetwork());
        Assertions.assertEquals(PolicyType.SINGLE, wallet.getPolicyType());
        Assertions.assertEquals(ScriptType.P2WPKH, wallet.getScriptType());
        Assertions.assertEquals(1, wallet.getDefaultPolicy().getNumSignaturesRequired());
        Assertions.assertEquals("m/84'/2'/0'", wallet.getKeystores().get(0).getKeyDerivation().getDerivationPath());

        // decrypt the seed with the file key and confirm the exact mnemonic round-trips
        Wallet copy = wallet.copy();
        copy.decrypt(walletAndKey.getKey());
        Keystore copyKeystore = copy.getKeystores().get(0);
        Assertions.assertEquals(MNEMONIC, copyKeystore.getSeed().getMnemonicString().asString());

        // desktop re-derives fingerprint/xpub from the decrypted seed (as the app does on
        // open); they must match what mobile wrote
        Keystore derived = Keystore.fromSeed(copyKeystore.getSeed(), copyKeystore.getKeyDerivation().getDerivation());
        Assertions.assertEquals("73c5da0a", derived.getKeyDerivation().getMasterFingerprint());
        Assertions.assertEquals(mobileXpub, derived.getExtendedPublicKey().toString());

        Keystore keystore = wallet.getKeystores().get(0);
        keystore.setKeyDerivation(derived.getKeyDerivation());
        keystore.setExtendedPublicKey(derived.getExtendedPublicKey());
        try {
            wallet.checkWallet();
        } catch(Exception e) {
            Assertions.fail("mobile-exported wallet must be valid on desktop: " + e.getMessage());
        }
    }
}
