package com.sparrowwallet.mobile.crypto

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Parity harness against the desktop wallet (drongo).
 *
 * Vectors are generated by GoldenVectorGeneratorTest in the sparrow-ltc desktop repo:
 *   cd ../sparrow && ./gradlew :drongo:test --tests '*GoldenVectorGenerator*'
 *
 * Currently validates structure and LTC network encoding of the vectors themselves.
 * As :core-crypto porting proceeds, each derivation step (BIP39 seed, BIP32 keys,
 * addresses, WIF, MWEB view keys) gets asserted here byte-for-byte against the vectors.
 */
class GoldenVectorTest {
    private val vectors = Json.parseToJsonElement(
        File("../vectors/golden-vectors.json").readText()
    ).jsonObject

    private val expectedPathPrefixes = mapOf(
        "P2PKH" to "m/44'/2'/0'",
        "P2SH_P2WPKH" to "m/49'/2'/0'",
        "P2WPKH" to "m/84'/2'/0'",
        "MWEB" to Litecoin.MWEB_DERIVATION_PATH
    )

    private val expectedAddressPrefixes = mapOf(
        "P2PKH" to "L",
        "P2SH_P2WPKH" to "M",
        "P2WPKH" to "${Litecoin.BECH32_HRP}1q",
        "MWEB" to "${Litecoin.MWEB_HRP}1"
    )

    @Test
    fun vectorsAreLitecoinMainnet() {
        assertEquals("mainnet", vectors["network"]!!.jsonPrimitive.content)
    }

    @Test
    fun allSeedsAndScriptTypesPresent() {
        val seeds = vectors["seeds"]!!.jsonArray
        assertEquals(3, seeds.size)
        for(seed in seeds) {
            val scriptTypes = seed.jsonObject["scriptTypes"]!!.jsonArray
            assertEquals(expectedPathPrefixes.keys, scriptTypes.map { it.jsonObject["scriptType"]!!.jsonPrimitive.content }.toSet())
        }
    }

    @Test
    fun derivationPathsMatchLtcCoinType() {
        forEachScriptType { seedName, scriptType, entry ->
            val path = entry["derivationPath"]!!.jsonPrimitive.content
            assertEquals(expectedPathPrefixes[scriptType], path, "seed=$seedName scriptType=$scriptType")
        }
    }

    @Test
    fun addressesUseLtcEncodings() {
        forEachScriptType { seedName, scriptType, entry ->
            val prefix = expectedAddressPrefixes[scriptType]!!
            val receive = entry["receiveAddresses"]!!.jsonArray.map { it.jsonPrimitive.content }
            val change = entry["changeAddresses"]!!.jsonArray.map { it.jsonPrimitive.content }
            assertEquals(5, receive.size, "seed=$seedName scriptType=$scriptType")
            assertEquals(3, change.size, "seed=$seedName scriptType=$scriptType")
            for(address in receive + change) {
                assertTrue(address.startsWith(prefix), "seed=$seedName scriptType=$scriptType address=$address expected prefix=$prefix")
            }
        }
    }

    @Test
    fun mwebViewKeysHaveCorrectShape() {
        forEachScriptType { seedName, scriptType, entry ->
            val scanSecret = entry["mwebScanSecret"]!!.jsonPrimitive.content
            val spendPubKey = entry["mwebSpendPubKey"]!!.jsonPrimitive.content
            assertEquals(64, scanSecret.length, "seed=$seedName scriptType=$scriptType scan secret must be 32 bytes")
            assertEquals(66, spendPubKey.length, "seed=$seedName scriptType=$scriptType spend pubkey must be 33 bytes")
            assertTrue(spendPubKey.startsWith("02") || spendPubKey.startsWith("03"),
                "seed=$seedName scriptType=$scriptType spend pubkey must be a compressed point")
        }
    }

    @Test
    fun masterFingerprintsAreStableAcrossScriptTypes() {
        for(seed in vectors["seeds"]!!.jsonArray) {
            val fingerprint = seed.jsonObject["masterFingerprint"]!!.jsonPrimitive.content
            assertEquals(8, fingerprint.length)
        }
    }

    private fun forEachScriptType(action: (seedName: String, scriptType: String, entry: kotlinx.serialization.json.JsonObject) -> Unit) {
        for(seed in vectors["seeds"]!!.jsonArray) {
            val seedName = seed.jsonObject["name"]!!.jsonPrimitive.content
            for(entry in seed.jsonObject["scriptTypes"]!!.jsonArray) {
                val obj = entry.jsonObject
                action(seedName, obj["scriptType"]!!.jsonPrimitive.content, obj)
            }
        }
    }
}
