package com.sparrowwallet.mobile.storage

import com.sparrowwallet.mobile.crypto.Bip39
import com.sparrowwallet.mobile.crypto.HDKey
import com.sparrowwallet.mobile.crypto.toHex
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Golden-vector parity with desktop Sparrow's own StorageTest: the fixture
 * `sparrow-single-seed-wallet` ships in the desktop repo's test resources
 * (password "pass", Argon2 TEST_PARAMS — real desktop files use SPRW1_PARAMS).
 * Every asserted value below is asserted identically by the desktop test,
 * and the decrypted mnemonic must re-derive the exact xpub desktop recorded.
 */
class SparrowImportTest {
    private val fileBytes = File("../vectors/sparrow-single-seed-wallet").readBytes()

    @Test
    fun importsDesktopEncryptedSeedWallet() {
        val imported = SparrowImport.importFile(fileBytes, "pass", SparrowImport.TEST_PARAMS)

        assertEquals("testd2", imported.name)
        assertEquals("P2WPKH", imported.scriptType)
        assertEquals("m/84'/0'/3'", imported.derivationPath)
        assertEquals("BIP39", imported.seedType)
        assertFalse(imported.needsPassphrase)
        assertTrue(Bip39.isValid(imported.mnemonic), "decrypted mnemonic must be valid BIP39")

        // end-to-end: the decrypted seed re-derives the exact keys desktop's StorageTest
        // records (fingerprint via its policy "pkh(60bcd3a7)", plus the account xpub).
        // This old-format fixture carries no masterFingerprint/xpub fields in JSON.
        val master = HDKey.fromSeed(Bip39.seed(imported.mnemonic, ""))
        assertEquals("60bcd3a7", master.fingerprint.toHex())
        val account = master.derivePath("m/84'/0'/3'")
        assertEquals(
            "xpub6BrhGFTWPd3DXo8s2BPxHHzCmBCyj8QvamcEUaq8EDwnwXpvvcU9LzpJqENHcqHkqwTn2vPhynGVoEqj3PAB3NxnYZrvCsSfoCniJKaggdy",
            account.xpub()
        )
    }

    @Test
    fun wrongPasswordFailsCleanly() {
        val error = assertFailsWith<SparrowImport.ImportException> {
            SparrowImport.importFile(fileBytes, "wrong", SparrowImport.TEST_PARAMS)
        }
        assertTrue(error.message!!.contains("password"))
    }

    @Test
    fun detectsEncryptedHeader() {
        assertTrue(SparrowImport.isEncryptedSparrowFile(fileBytes))
        assertFalse(SparrowImport.isEncryptedSparrowFile("""{"name":"x"}""".toByteArray()))
        assertFalse(SparrowImport.isEncryptedSparrowFile(ByteArray(10)))
    }

    @Test
    fun importsSeparateSeedMwebWalletVector() {
        // regenerated by the sparrow repo's SparrowLinkExportTest.exportsSeparateSeedMwebWallet
        val vector = File("../vectors/desktop-link-mweb-vector-wallet")
        assertTrue(vector.exists(), "run desktop SparrowLinkExportTest first to regenerate the vector")

        val imported = SparrowImport.importFile(vector.readBytes(), "pass", SparrowImport.TEST_PARAMS)
        assertEquals("Link Private Test", imported.name)
        assertEquals("MWEB", imported.scriptType)
        assertEquals("m/1000'", imported.derivationPath)
        assertEquals(
            "legal winner thank year wave sausage worth useful legal winner thank yellow",
            imported.mnemonic
        )
    }

    @Test
    fun importsSparrowLinkPushVector() {
        // the exact bytes desktop's Link push sends, regenerated by the sparrow repo's
        // SparrowLinkExportTest (password "pass", TEST argon2 params)
        val vector = File("../vectors/desktop-link-vector-wallet")
        assertTrue(vector.exists(), "run desktop SparrowLinkExportTest first to regenerate the vector")

        val imported = SparrowImport.importFile(vector.readBytes(), "pass", SparrowImport.TEST_PARAMS)
        assertEquals("Link Test", imported.name)
        assertEquals("mainnet", imported.network)
        assertEquals("P2WPKH", imported.scriptType)
        assertEquals("m/84'/2'/0'", imported.derivationPath)
        assertEquals("73c5da0a", imported.masterFingerprint)
        assertEquals(
            "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            imported.mnemonic
        )
    }
}
